name: CI/CD Workflow

on:
  push:
    branches:
      - main
  workflow_dispatch:
    inputs:
      environment:
        description: 'Deploy environment (QA or Prod)'
        required: true
        default: 'QA'

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Dev Environment Info
        run: |
          echo "Dev"
          echo "SHA: ${{ github.sha }}"

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Deploy Environment Info
        run: |
          echo "${{ github.event.inputs.environment }}"
          echo "SHA: ${{ github.sha }}"
