name: Dev

on:
  push:
    branches:
      - main
  workflow_dispatch:


jobs:
  build:
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: version
        run: echo "1.0.0" > version.txt

      - name: Echo Dev Environment Info
        run: |
          echo "Dev"
          echo "SHA: ${{ github.sha }}"

      - name: Tag Deployment
        run: |
          DATE_TIME=$(date +%Y%m%d%H%M%S)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag dev-${DATE_TIME}
          git push origin dev-${DATE_TIME}
