name: Prod

on:
  workflow_dispatch:
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Deploy Environment Info
        run: |
          echo "SHA: ${{ github.sha }}"
