name: Prod

on:
  workflow_dispatch:
   
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Deploy Environment Info
        run: |
          if [[ ! ${{ github.event.inputs.tag }} =~ ^prod- ]]; then
            echo "Invalid tag name. Tag name must start with 'prod-'"
            exit 1
          fi
          echo "Deploying to Prod environment..."
          echo "Using sha: ${{ github.sha }}"
      
      - name: Tag Deployment
        run: |
          DATE_TIME=$(date +%Y%m%d%H%M%S)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag prod-${DATE_TIME}
          git push origin prod-${DATE_TIME}
