name: Prod
run-name: Deploy to Prod - ${{ github.ref_name }} by @${{ github.actor }}
on:
  workflow_dispatch:
jobs:
  deploy-prod:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: rickstaa/action-get-semver@v1
        id: get_semver
        with:
          bump_level: "patch"
    
      - name: Echo Deploy Environment Info
        run: |
          echo "Deploying to Prod environment..."
          echo "Using sha: ${{ github.sha }}"
          echo "Deploying version: ${{ steps.get_semver.outputs.current_version }}"
