name: QA

on:
  workflow_run:
    workflows: [Dev]
    types:
      - completed
  workflow_dispatch:

jobs:
  deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Deploy Environment Info
        run: |
          echo "SHA: ${{ github.sha }}"