name: Dev

on:
  workflow_dispatch:

jobs:
  deploy-qa:
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch' && github.event.inputs.deploy_qa == 'QA'

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Echo Deploy Environment Info
        run: |
          echo "${{ github.event.inputs.environment }}"
          echo "SHA: ${{ github.sha }}"