name: QA

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: 'Tag to deploy (e.g., dev-YYYYMMDDHHMMSS)'
    #     required: true

jobs:
  deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      
      - uses: rickstaa/action-get-semver@v1
        id: get_semver

      - name: Echo Deploy Environment Info
        run: |
          echo "Deploying to QA environment..."
          echo "Using sha: ${{ github.sha }}"

      - name: Tag Deployment
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag qa-${{ steps.get_semver.outputs.next_version }}
          git push origin qa-${{ steps.get_semver.outputs.next_version }}
  