name: QA

on:
  workflow_dispatch:
    # inputs:
    #   tag:
    #     description: 'Tag to deploy (e.g., dev-YYYYMMDDHHMMSS)'
    #     required: true

jobs:
  deploy-qa:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        # with:
          # ref: ${{ github.event.inputs.tag }}

      - name: Echo Deploy Environment Info
        run: |
          echo "Deploying to QA environment..."
          echo "Using tag: ${{ github.event.inputs.tag }}"

      - name: Tag Deployment
        run: |
          DATE_TIME=$(date +%Y%m%d%H%M%S)
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag qa-${DATE_TIME}
          git push origin qa-${DATE_TIME}
  